In [2]:
import pandas as pd
import seaborn as sns
df= sns.load_dataset('tips')

In [3]:
from sklearn.preprocessing import LabelEncoder
encoder_time= LabelEncoder()

encoded_data = encoder_time.fit_transform(df['time'])

In [4]:
print('classes',encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [5]:
encoded_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [6]:
for category,number in zip (encoder_time.classes_, range(len(encoder_time.classes_))):
    print(category ,"-----------",number)

Dinner ----------- 0
Lunch ----------- 1

In [7]:
encoder_day= LabelEncoder()

encoded_day_data = encoder_day.fit_transform(df['day'])

In [8]:
print('classes',encoder_day.classes_)

classes ['Fri' 'Sat' 'Sun' 'Thur']

In [9]:
for category,number in zip (encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category ,"-----------",number)

Fri ----------- 0
Sat ----------- 1
Sun ----------- 2
Thur ----------- 3

In [13]:
encoder_day.inverse_transform([0,1,2,3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe= OneHotEncoder(sparse_output=False,drop='first')
ohe_encorder=ohe.fit_transform(df[['sex','smoker']])
ohe_encorder

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.]])

In [20]:
df1=pd.DataFrame(ohe_encorder,columns=ohe.get_feature_names_out())
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [21]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [23]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [25]:
power=FunctionTransformer(np.log10)
power.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [27]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

X = np.array([
    [-1],
    [0],
    [3],
    [5],
    [10],
    [50],
])
pt= PowerTransformer(method='yeo-johnson')

X_transformed = pt.fit_transform(X)
print('Original:')
print(X.ravel())

print('\nTransformed:')
print(np.round(X_transformed.ravel(),3))
print('\nLearned lambda:')
print(pt.lambdas_)

Original:
[-1  0  3  5 10 50]

Transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[0.09126797]

In [29]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

y = np.array([
    [1],
    [1],
    [3],
    [5],
    [10],
    [50],
])
pt= PowerTransformer(method='box-cox')

y_transformed = pt.fit_transform(y)
print('Original:')
print(y.ravel())

print('\nTransformed:')
print(np.round(y_transformed.ravel(),3))
print('\nLearned lambda:')
print(pt.lambdas_)

Original:
[ 1  1  3  5 10 50]

Transformed:
[-1.205 -1.205 -0.15   0.255  0.73   1.574]

Learned lambda:
[-0.23784507]

In [42]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Shrey', 'Rahul', 'Priya', 'Neha'],
    'Age': [20, 21, np.nan, 19, 22, 20],
    'Marks': [85, 90, 78, np.nan, 88, 95],
    'Gender': ['Male', 'Female', 'Male', np.nan, 'Female', 'Female'],
    'City': ['Bhopal', 'Indore', 'Bhopal', 'Dewas', np.nan, 'Indore'],
    'Department': ['AIML', 'CSE', 'AIML', 'IT', 'CSE', np.nan]
})

print(df)

    Name   Age  Marks  Gender    City Department
0   Aman  20.0   85.0    Male  Bhopal       AIML
1   Riya  21.0   90.0  Female  Indore        CSE
2  Shrey   NaN   78.0    Male  Bhopal       AIML
3  Rahul  19.0    NaN     NaN   Dewas         IT
4  Priya  22.0   88.0  Female     NaN        CSE
5   Neha  20.0   95.0  Female  Indore        NaN

In [44]:
from sklearn.impute import SimpleImputer

In [39]:
from sklearn.impute import SimpleImputer
import numpy as np

df = df[['Age', 'Marks']]

imputer = SimpleImputer(strategy='mean')
df = imputer.fit_transform(X)

print(df)

[[20.  85. ]
 [21.  90. ]
 [20.4 78. ]
 [19.  87.2]
 [22.  88. ]
 [20.  95. ]]

In [45]:
df

    Name   Age  Marks  Gender    City Department
0   Aman  20.0   85.0    Male  Bhopal       AIML
1   Riya  21.0   90.0  Female  Indore        CSE
2  Shrey   NaN   78.0    Male  Bhopal       AIML
3  Rahul  19.0    NaN     NaN   Dewas         IT
4  Priya  22.0   88.0  Female     NaN        CSE
5   Neha  20.0   95.0  Female  Indore        NaN